name: Build
on:
  push:
    branches: [ "rockpi-4-kernel5.10.110" ]
  pull_request:
    branches: [ "rockpi-4-kernel5.10.110" ]

  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '**.md'
  #     - .gitignore
  #     - 'docs/**'
  #     - 'theme/**'
  #     - book.toml
  #     - .github/workflows/docs.yaml
  #     - container/Dockerfile
  #     - .github/workflows/deploy-image.yaml
  # pull_request:
  #   paths-ignore:
  #     - '**.md'
  #     - .gitignore
  #     - 'docs/**'
  #     - 'theme/**'
  #     - book.toml
  #     - .github/workflows/docs.yaml
  #     - container/Dockerfile
  #     - .github/workflows/deploy-image.yaml

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: sansltd/radxa-kernel-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run BSP Build
        run: | 
          ./bsp --native-build --revision 13 linux rockchip  
          mkdir dist
          mv linux-headers-*_arm64.deb dist
          mv linux-image-*_arm64.deb dist
          mv linux-image-rock-4se_*.deb dist
          mv ./linux/arch/arm64/boot/dts/rockchip/overlay/mipi-csi.dtbo dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: 
            dist/*